### PR TITLE
Cloning the-next-web website

### PR DESCRIPTION
**Pull request by uzorjchibuzor**
We are putting the responsive design lessons to action. @talihomz

### CODE REVIEW

**Comment by talihomz** [comment]
Hi @uzorjchibuzor @MrObele 

Great work cloning The Next Web's page, it looks awesome!

Some comments on the code:
1. [Here](https://github.com/MrObele/the-next-web-clone/blob/a1934be36bacc5ca13a19828364ac93fa58ed679/index.html#L84-L100), the nesting of an `a` tag inside another `a` tag might be unnecessary.

2. The `article` tag is mostly used to show a blog post, comment, news story. You can avoid overusing it by using a `div` where necessary. See [this article](https://www.w3schools.com/tags/tag_article.asp) for more information on the same.

**Comment by uzorjchibuzor** [comment]
I just checked the highlighted section and :see_no_evil: 
I think what we wanted was to make it a clickable element. Looking back now, cursor:pointer could've fixed that.

**Comment by uzorjchibuzor** [comment]
@talihomz  Are you giving it a go?

**Comment by arielcamus** [comment]
@uzorjchibuzor please submit a new code review request to get a 👍 here

**Comment by uzorjchibuzor** [comment]
> @uzorjchibuzor please submit a new code review request to get a  here

Lol. Will do. thanks

**Review by rvvergara — CHANGES_REQUESTED** [review]
Hi Uzor,

Glad to be reviewing your code :) You did an awesome job. Here are just some of the things that can be improved:

1. Kindly fill out the README to include author name, say something about the project and link to a live demo (if any, better if there is, you may use githack for this)

2. All images and the font files should go into an "assets" folder so the project is more organized

3. Running index.html through the W3C markup validator returned some errors (based on markup standards), kindly run it through the validator again and see these errors (and please edit the code accordingly) - 

https://github.com/MrObele/the-next-web-clone/blob/8df028f2cee629225b3f0536860ec66ac66d73b3/index.html

4. The images are too fluid (i.e, they get warped as I adjust the size of the browser.. The responsiveness of the columns are good, I suggest just make the images responsive but not fluid:
(https://raw.githack.com/MrObele/the-next-web-clone/8df028f2cee629225b3f0536860ec66ac66d73b3/index.html)


5. I like the way you structured the CSS. The way you split the styles for each part of the webpage (i.e, latest news section). Just a small suggestion, there are some common styles like the font-family of Shentox, sans-serif for .latest-news article span (line 283) and .overlay p.topic (line 197). Not a deal breaker (I understand how chaotic CSS can be especially if you've written so many lines). It will just a great thing to do to make it easy for you later on to adjust stuff. But other than that, your CSS code is ok. 
(https://github.com/MrObele/the-next-web-clone/blob/8df028f2cee629225b3f0536860ec66ac66d73b3/stylesheets/style.css)

**Comment by talihomz** [comment]
Its a 👍 from me.

**Review by talihomz — APPROVED** [review]
This looks good so far!

**Pull request merged**
